(require :asdf)
(handler-bind ((warning #'muffle-warning))
  (let ((*standard-output* (make-broadcast-stream))) (asdf:load-system :cairn)))
(in-package :cairn)
(let ((repo (open-repository "/tmp/gitpack")))
  (format t "~&=== cairn log (from pack) ===~%")
  (dolist (e (log-commits repo)) (format t "~a ~a~%" (subseq (car e) 0 7) (commit-summary (cdr e))))
  (format t "~%=== cat-file data.txt (HEAD tree) ===~%")
  (let* ((entry (find "data.txt" (ls-tree repo "HEAD") :key #'tree-entry-name :test #'string=)))
    (multiple-value-bind (type content) (read-object repo (tree-entry-sha entry))
      (format t "type ~a, ~d bytes, sha-check ~a~%" type (length content)
              (string= (tree-entry-sha entry) (hash-object type content)))
      (format t "first 3 lines: ~a~%" (subseq (ascii content) 0 21))))
  (format t "~%=== the DELTA object non ===~%")
  (multiple-value-bind (type content) (read-object repo "non")
    (format t "resolved type ~a, ~d bytes, sha-verifies ~a~%" type (length content)
            (string= "non" (hash-object type content)))))
