(require :asdf)
(dolist (f '("packages" "sha1" "inflate" "objects" "refs" "repository" "plumbing"))
  (load (compile-file (format nil "/home/claude/cairn/src/~a.lisp" f) :verbose nil :print nil)))
(in-package :cairn)
(let ((repo (open-repository "/tmp/gittest")))
  (format t "~&HEAD = ~a~%~%=== cairn log ===~%" (head-commit repo))
  (dolist (e (log-commits repo))
    (format t "~a ~a~%" (subseq (car e) 0 7) (commit-summary (cdr e))))
  (format t "~%=== cairn cat-file HEAD ===~%~a" (cat-file-string repo "HEAD"))
  (format t "~%=== cairn ls-tree HEAD ===~%")
  (dolist (te (ls-tree repo "HEAD"))
    (format t "~a ~a ~a~%" (tree-entry-mode te) (subseq (tree-entry-sha te) 0 7) (tree-entry-name te)))
  (format t "~%=== refs ===~%")
  (dolist (r (list-refs repo)) (format t "~a -> ~a~%" (car r) (subseq (cdr r) 0 7))))
